name: Compose Inputs
description: Compose workflow inputs
inputs:
  environments:
    required: false
    description: A YAML list of environment names
    default: ''
  environments_tags:
    required: false
    description: A YAML encoded map of environment names to a list of tags for that environment
    default: ''
  environments_variables:
    required: false
    description: A YAML encoded map of environment names to a list of Terraform Cloud variable objects
    default: ''
  name:
    required: false
    description: Workspace name, or workspace name prefix in the case of a multi-environment configuration
    default: "${{ github.event.repository.name }}"
  tags:
    required: false
    description: A YAML encoded list of tags that apply to all workspaces
    default: ''
outputs:
  workspaces:
    description: Workspaces
  workspace_tags:
    description: Workspace tags
  workspace_variables:
    description: Workspace variables
runs:
  using: docker
  image: Dockerfile   